name: validate renovate

on:
  push:
    paths:
      - 'renovate.json'
      - '.github/workflows/renovate-validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v3

      - name: install
        run: |
          npm install -g renovate

      - name: validate
        run: |
          renovate-config-validator
